using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using UnityEditor;
using UnityEngine;

namespace PrefabPalette 
{
    /// <summary>
    /// Scriptable object that holds the editable list of collection names.
    /// </summary>
    public class PrefabCollectionList : ScriptableObject
    {
        /// <summary>
        /// Editable list of collection names exposed in CollectionsListInspector.
        /// </summary>
        public List<string> collectionNames = new List<string>();

        private static PrefabCollectionList instance; 

        public static PrefabCollectionList Instance 
        { 
            get 
            {
                if (instance == null)
                {
                    instance = Helpers.LoadOrCreateAsset<PrefabCollectionList>(PathDr.GetGeneratedFolderPath, "CollectionNamesList.asset", out _);
                }

                return instance;
            } 
        }

        /// <summary>
        /// Ensures list matches Enum values.
        /// </summary>
        public void SyncListWithEnum()
        {
            // Ensure the enum and list is synced
            collectionNames.Clear();
            collectionNames.AddRange(Enum.GetValues(typeof(CollectionName))
                      .Cast<CollectionName>()
                      .Where(e => e != CollectionName.None) // Exclude .None
                      .Select(e => e.ToString())); // Convert enums to strings
        }

        /// <summary>
        /// Writes collection names list to a file as an enum.
        /// </summary>
        public void GenerateEnum()
        {
            // Name validation
            List<string> validNames = collectionNames
                .Where(i => !string.IsNullOrWhiteSpace(i)) // Ensure not empty
                .Distinct() // Ensure is unique
                .Select(Helpers.SanitiseEnumName) // Enure valid enum name
                .ToList(); // Create new list

            // File creation
            string content = "// *!DO NOT MANUALLY EDIT OR DELETE!*\n";
            content += $"// This File Is Auto-Generated by {nameof(PrefabCollectionList)}.cs\n";
            content += "namespace PrefabPalette {\n";
            content += "    public enum CollectionName {\n        None,\n";
            foreach (var name in validNames)
            {
                content += $"        {name},\n";
            }
            content += "    }\n}";

            var path = Path.Combine(PathDr.GetGeneratedFolderPath, "CollectionName.cs");
            File.WriteAllText(path, content);

            AssetDatabase.Refresh();
            UnityEditor.Compilation.CompilationPipeline.RequestScriptCompilation();
        }

        /// <summary>
        /// Searches the collection folder for existing collections,
        /// updates the list, and regenerates the enum file.
        /// </summary>
        public void Sync()
        {
            SyncListWithEnum();

            List<string> collectionsInFolder = PrefabCollection
                .GetAllCollectionsInFolder
                .Select(e => e.name.Replace("_PrefabCollection", ""))
                .Distinct()
                .ToList();

            var oldSet = new HashSet<string>(collectionNames);
            var newSet = new HashSet<string>(collectionsInFolder);

            bool hasChanged = !newSet.IsSubsetOf(oldSet);

            if (!hasChanged)
                return;

            oldSet.UnionWith(newSet);
            collectionNames = oldSet.ToList();
            GenerateEnum();
        }
    }
}
